---
- name: Download daemonize archive.
  get_url:
    url: "https://github.com/bmc/daemonize/archive/release-{{ daemonize_version }}.tar.gz"
    dest: "{{ workspace }}/daemonize-{{ daemonize_version }}.tar.gz"

- name: Expand daemonize archive.
  command: >
    tar -zxf {{ workspace }}/daemonize-{{ daemonize_version }}.tar.gz
    chdir={{ workspace }}
    creates={{ workspace }}/daemonize-release-{{ daemonize_version }}/INSTALL

- name: Check if daemonize is installed.
  command: "env \"PATH=$PATH:{{daemonize_install_path}}:{{daemonize_install_path}}/sbin:{{daemonize_install_path}}/bin:{{daemonize_install_path}}/local/sbin:{{daemonize_install_path}}/local/bin\" which daemonize"
  changed_when: false
  failed_when: false
  register: daemonize_installed

- name: Build daemonize.
  command: >
    {{ item }}
    chdir={{ workspace }}/daemonize-release-{{ daemonize_version }}
  when: daemonize_installed|failed
  with_items:
    - ./configure
    - "make prefix={{ daemonize_install_path }}"
    - "make prefix={{ daemonize_install_path }} install"
  sudo: yes
